language: python
before_script:
- pip install flake8
python:
#  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: python setup.py install
# command to run tests
script:
- python setup.py test --addopts -v
- flake8 --max-complexity 10 --exclude tests